### PR TITLE
PBR's are legal if they are limited edition

### PR DESCRIPTION
**Pull request by JackyChiu**

### CODE REVIEW

**Comment by Tricktionary** [comment]
LOL IDK ABOUT THIS

**Comment by vikrambombhi** [comment]
I think if we say that PBRs cant be used to block ices we can merge this

**Comment by samjjc** [comment]
I don't think we're emphasizing how low tier pbr actually is

**Comment by JackyChiu** [comment]
Since you guys aren't being good sports about this, I'm just going to close this.

**Pull request merged**
